project:
  type: website
  output-dir: docs

website:
  title: "Anna Ramji"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: blog.qmd
        text: Projects + Blog
 #     - href: resources.qmd
 #       text: Resources
  page-footer:
#  background: light
    left: "Copyright 2024, Anna Ramji"
    right:
     - icon: github
       href: https://github.com/annaramji

format:
  html:
    theme: 
      - styles.scss
    #  - minty
    # - dark: solar
  #  css: styles.css
    mainfont: Nunito
    toc: true
    page-layout: full

editor: visual

